services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eprint-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - storage_data:/var/www/storage



  nginx:
    image: nginx:latest
    container_name: eprint-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - storage_data:/var/www/storage
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro


volumes:
  storage_data: